### PR TITLE
Fixes (All Images + Links + Some Spelling)

### PR DESCRIPTION
**Pull request by MitchellPT**
Spelling + Image Fixes

### CODE REVIEW

**Comment by MitchellPT** [comment]
*I didnt change the cPanel links because the do redirect to the correct place.

**Comment by MitchellPT** [comment]
mass changed all
https://raw.githubusercontent.com/HexaneNetworks/help-assets/master/assets/png/
to
https://raw.githubusercontent.com/HexaneNetworks/help-assets/master/assets/
fixing images.

**Comment by MitchellPT** [comment]
Changed cpanel.hexanenetworks.com to cpanel.hexaneweb.com

**Comment by JamesLovern** [comment]
LGTM!

**Pull request merged**
